const keyValuePairs = [
  { John: 'New York, NY' },
  { Jane: 'Los Angeles, CA' },
  { Bob: 'Chicago, IL' },
  { Alice: 'Houston, TX' },
  { Tom: 'Phoenix, AZ' },
  { Emma: 'Philadelphia, PA' },
  { David: 'San Antonio, TX' },
  { Sophia: 'San Diego, CA' },
  { Michael: 'Dallas, TX' },
  { Olivia: 'San Jose, CA' },
  { Daniel: 'Austin, TX' },
  { Ava: 'Jacksonville, FL' },
  { James: 'Fort Worth, TX' },
  { Mia: 'Columbus, OH' },
  { William: 'San Francisco, CA' },
  { Isabella: 'Charlotte, NC' },
  { Joseph: 'Indianapolis, IN' },
  { Emily: 'Seattle, WA' },
  { Charles: 'Denver, CO' },
  { Abigail: 'Boston, MA' },
  { Thomas: 'El Paso, TX' },
  { Madison: 'Detroit, MI' },
  { Robert: 'Nashville, TN' },
  { Elizabeth: 'Portland, OR' },
  { Andrew: 'Memphis, TN' },
  { Chloe: 'Oklahoma City, OK' },
  { Ryan: 'Las Vegas, NV' },
  { Ella: 'Louisville, KY' },
  { Joshua: 'Baltimore, MD' },
  { Avery: 'Milwaukee, WI' },
];

const input = keyValuePairs.map(obj => Object.entries(obj)[0]);

export const arrInput = [
  ['John', 'New York, NY'],
  ['Jane', 'Los Angeles, CA'],
  ['Bob', 'Chicago, IL'],
  ['Alice', 'Houston, TX'],
  ['Tom', 'Phoenix, AZ'],
  ['Emma', 'Philadelphia, PA'],
  ['David', 'San Antonio, TX'],
  ['Sophia', 'San Diego, CA'],
  ['Michael', 'Dallas, TX'],
  ['Olivia', 'San Jose, CA'],
  ['Daniel', 'Austin, TX'],
  ['Ava', 'Jacksonville, FL'],
  ['James', 'Fort Worth, TX'],
  ['Mia', 'Columbus, OH'],
  ['William', 'San Francisco, CA'],
  ['Isabella', 'Charlotte, NC'],
  ['Joseph', 'Indianapolis, IN'],
  ['Emily', 'Seattle, WA'],
  ['Charles', 'Denver, CO'],
  ['Abigail', 'Boston, MA'],
  ['Thomas', 'El Paso, TX'],
  ['Madison', 'Detroit, MI'],
  ['Robert', 'Nashville, TN'],
  ['Elizabeth', 'Portland, OR'],
  ['Andrew', 'Memphis, TN'],
  ['Chloe', 'Oklahoma City, OK'],
  ['Ryan', 'Las Vegas, NV'],
  ['Ella', 'Louisville, KY'],
  ['Joshua', 'Baltimore, MD'],
  ['Avery', 'Milwaukee, WI'],
  ['Avery', 'Baltimore, MD'],
];
